export default function citiesData() {
  const telAviv = {
    location: {
      name: "Tel Aviv-Yafo",
      region: "Tel Aviv",
      country: "Israel",
      lat: 32.07,
      lon: 34.76,
      tz_id: "Asia/Jerusalem",
      localtime_epoch: 1639661871,
      localtime: "2021-12-16 15:37",
    },
    current: {
      last_updated_epoch: 1639661400,
      last_updated: "2021-12-16 15:30",
      temp_c: 18.0,
      temp_f: 64.4,
      is_day: 1,
      condition: {
        text: "Moderate rain",
        icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
        code: 1189,
      },
      wind_mph: 10.5,
      wind_kph: 16.9,
      wind_degree: 200,
      wind_dir: "SSW",
      pressure_mb: 1016.0,
      pressure_in: 30.0,
      precip_mm: 2.5,
      precip_in: 0.1,
      humidity: 56,
      cloud: 50,
      feelslike_c: 18.0,
      feelslike_f: 64.4,
      vis_km: 10.0,
      vis_miles: 6.0,
      uv: 4.0,
      gust_mph: 20.6,
      gust_kph: 33.1,
    },
    forecast: {
      forecastday: [
        {
          date: "2021-12-16",
          date_epoch: 1639612800,
          day: {
            maxtemp_c: 17.7,
            maxtemp_f: 63.9,
            mintemp_c: 14.7,
            mintemp_f: 58.5,
            avgtemp_c: 16.3,
            avgtemp_f: 61.3,
            maxwind_mph: 15.2,
            maxwind_kph: 24.5,
            totalprecip_mm: 10.1,
            totalprecip_in: 0.4,
            avgvis_km: 9.7,
            avgvis_miles: 6.0,
            avghumidity: 63.0,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 92,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 3.0,
          },
          astro: {
            sunrise: "06:35 AM",
            sunset: "04:38 PM",
            moonrise: "02:46 PM",
            moonset: "03:59 AM",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "82",
          },
          hour: [
            {
              time_epoch: 1639605600,
              time: "2021-12-16 00:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11.4,
              wind_kph: 18.4,
              wind_degree: 170,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 9,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 6.8,
              dewpoint_f: 44.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.6,
              gust_kph: 29.9,
              uv: 1.0,
            },
            {
              time_epoch: 1639609200,
              time: "2021-12-16 01:00",
              temp_c: 15.5,
              temp_f: 59.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 181,
              wind_dir: "S",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 55,
              cloud: 19,
              feelslike_c: 15.5,
              feelslike_f: 59.9,
              windchill_c: 15.5,
              windchill_f: 59.9,
              heatindex_c: 15.5,
              heatindex_f: 59.9,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 20.4,
              gust_kph: 32.8,
              uv: 1.0,
            },
            {
              time_epoch: 1639612800,
              time: "2021-12-16 02:00",
              temp_c: 15.3,
              temp_f: 59.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 177,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 24,
              feelslike_c: 15.3,
              feelslike_f: 59.5,
              windchill_c: 15.3,
              windchill_f: 59.5,
              heatindex_c: 15.3,
              heatindex_f: 59.5,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 20.6,
              gust_kph: 33.1,
              uv: 1.0,
            },
            {
              time_epoch: 1639616400,
              time: "2021-12-16 03:00",
              temp_c: 15.0,
              temp_f: 59.0,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 173,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 57,
              cloud: 63,
              feelslike_c: 13.7,
              feelslike_f: 56.7,
              windchill_c: 13.7,
              windchill_f: 56.7,
              heatindex_c: 15.0,
              heatindex_f: 59.0,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 19.7,
              gust_kph: 31.7,
              uv: 1.0,
            },
            {
              time_epoch: 1639620000,
              time: "2021-12-16 04:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 185,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 55,
              cloud: 61,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 6.7,
              dewpoint_f: 44.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.3,
              gust_kph: 26.3,
              uv: 1.0,
            },
            {
              time_epoch: 1639623600,
              time: "2021-12-16 05:00",
              temp_c: 16.0,
              temp_f: 60.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 190,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 56,
              cloud: 16,
              feelslike_c: 16.0,
              feelslike_f: 60.8,
              windchill_c: 16.0,
              windchill_f: 60.8,
              heatindex_c: 16.0,
              heatindex_f: 60.8,
              dewpoint_c: 7.1,
              dewpoint_f: 44.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 15.2,
              gust_kph: 24.5,
              uv: 1.0,
            },
            {
              time_epoch: 1639627200,
              time: "2021-12-16 06:00",
              temp_c: 15.5,
              temp_f: 59.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 11.2,
              wind_kph: 18.0,
              wind_degree: 187,
              wind_dir: "S",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 59,
              cloud: 18,
              feelslike_c: 15.5,
              feelslike_f: 59.9,
              windchill_c: 15.5,
              windchill_f: 59.9,
              heatindex_c: 15.5,
              heatindex_f: 59.9,
              dewpoint_c: 7.5,
              dewpoint_f: 45.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 16.6,
              gust_kph: 26.6,
              uv: 1.0,
            },
            {
              time_epoch: 1639630800,
              time: "2021-12-16 07:00",
              temp_c: 14.7,
              temp_f: 58.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 183,
              wind_dir: "S",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 64,
              cloud: 22,
              feelslike_c: 13.3,
              feelslike_f: 55.9,
              windchill_c: 13.3,
              windchill_f: 55.9,
              heatindex_c: 14.7,
              heatindex_f: 58.5,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.8,
              gust_kph: 30.2,
              uv: 4.0,
            },
            {
              time_epoch: 1639634400,
              time: "2021-12-16 08:00",
              temp_c: 15.0,
              temp_f: 59.0,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 13.6,
              wind_kph: 22.0,
              wind_degree: 183,
              wind_dir: "S",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 65,
              cloud: 70,
              feelslike_c: 13.6,
              feelslike_f: 56.5,
              windchill_c: 13.6,
              windchill_f: 56.5,
              heatindex_c: 15.0,
              heatindex_f: 59.0,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 18.1,
              gust_kph: 29.2,
              uv: 4.0,
            },
            {
              time_epoch: 1639638000,
              time: "2021-12-16 09:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 189,
              wind_dir: "S",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 66,
              cloud: 74,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 9.2,
              dewpoint_f: 48.6,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 19.0,
              gust_kph: 30.6,
              uv: 4.0,
            },
            {
              time_epoch: 1639641600,
              time: "2021-12-16 10:00",
              temp_c: 16.2,
              temp_f: 61.2,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 196,
              wind_dir: "SSW",
              pressure_mb: 1019.0,
              pressure_in: 30.09,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 66,
              cloud: 80,
              feelslike_c: 16.2,
              feelslike_f: 61.2,
              windchill_c: 16.2,
              windchill_f: 61.2,
              heatindex_c: 16.2,
              heatindex_f: 61.2,
              dewpoint_c: 9.9,
              dewpoint_f: 49.8,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.8,
              gust_kph: 30.2,
              uv: 4.0,
            },
            {
              time_epoch: 1639645200,
              time: "2021-12-16 11:00",
              temp_c: 17.0,
              temp_f: 62.6,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 14.3,
              wind_kph: 23.0,
              wind_degree: 205,
              wind_dir: "SSW",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.9,
              precip_in: 0.04,
              humidity: 65,
              cloud: 90,
              feelslike_c: 17.0,
              feelslike_f: 62.6,
              windchill_c: 17.0,
              windchill_f: 62.6,
              heatindex_c: 17.0,
              heatindex_f: 62.6,
              dewpoint_c: 10.4,
              dewpoint_f: 50.7,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.6,
              gust_kph: 29.9,
              uv: 4.0,
            },
            {
              time_epoch: 1639648800,
              time: "2021-12-16 12:00",
              temp_c: 17.2,
              temp_f: 63.0,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 13.6,
              wind_kph: 22.0,
              wind_degree: 220,
              wind_dir: "SW",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 67,
              cloud: 89,
              feelslike_c: 17.2,
              feelslike_f: 63.0,
              windchill_c: 17.2,
              windchill_f: 63.0,
              heatindex_c: 17.2,
              heatindex_f: 63.0,
              dewpoint_c: 11.0,
              dewpoint_f: 51.8,
              will_it_rain: 0,
              chance_of_rain: 66,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 18.8,
              gust_kph: 30.2,
              uv: 4.0,
            },
            {
              time_epoch: 1639652400,
              time: "2021-12-16 13:00",
              temp_c: 17.3,
              temp_f: 63.1,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 229,
              wind_dir: "SW",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 69,
              cloud: 75,
              feelslike_c: 17.3,
              feelslike_f: 63.1,
              windchill_c: 17.3,
              windchill_f: 63.1,
              heatindex_c: 17.3,
              heatindex_f: 63.1,
              dewpoint_c: 11.5,
              dewpoint_f: 52.7,
              will_it_rain: 1,
              chance_of_rain: 92,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 19.7,
              gust_kph: 31.7,
              uv: 4.0,
            },
            {
              time_epoch: 1639656000,
              time: "2021-12-16 14:00",
              temp_c: 17.5,
              temp_f: 63.5,
              is_day: 1,
              condition: {
                text: "Moderate or heavy rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/356.png",
                code: 1243,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1017.0,
              pressure_in: 30.03,
              precip_mm: 2.5,
              precip_in: 0.1,
              humidity: 69,
              cloud: 64,
              feelslike_c: 17.5,
              feelslike_f: 63.5,
              windchill_c: 17.5,
              windchill_f: 63.5,
              heatindex_c: 17.5,
              heatindex_f: 63.5,
              dewpoint_c: 11.7,
              dewpoint_f: 53.1,
              will_it_rain: 1,
              chance_of_rain: 92,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7.0,
              vis_miles: 4.0,
              gust_mph: 20.6,
              gust_kph: 33.1,
              uv: 4.0,
            },
            {
              time_epoch: 1639659600,
              time: "2021-12-16 15:00",
              temp_c: 17.7,
              temp_f: 63.9,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 239,
              wind_dir: "WSW",
              pressure_mb: 1017.0,
              pressure_in: 30.04,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 68,
              cloud: 82,
              feelslike_c: 17.7,
              feelslike_f: 63.9,
              windchill_c: 17.7,
              windchill_f: 63.9,
              heatindex_c: 17.7,
              heatindex_f: 63.9,
              dewpoint_c: 11.7,
              dewpoint_f: 53.1,
              will_it_rain: 0,
              chance_of_rain: 68,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 4.0,
            },
            {
              time_epoch: 1639663200,
              time: "2021-12-16 16:00",
              temp_c: 17.6,
              temp_f: 63.7,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 236,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.05,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 69,
              cloud: 72,
              feelslike_c: 17.6,
              feelslike_f: 63.7,
              windchill_c: 17.6,
              windchill_f: 63.7,
              heatindex_c: 17.6,
              heatindex_f: 63.7,
              dewpoint_c: 11.8,
              dewpoint_f: 53.2,
              will_it_rain: 1,
              chance_of_rain: 91,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 13.4,
              gust_kph: 21.6,
              uv: 4.0,
            },
            {
              time_epoch: 1639666800,
              time: "2021-12-16 17:00",
              temp_c: 16.5,
              temp_f: 61.7,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 234,
              wind_dir: "SW",
              pressure_mb: 1018.0,
              pressure_in: 30.06,
              precip_mm: 1.2,
              precip_in: 0.05,
              humidity: 69,
              cloud: 85,
              feelslike_c: 16.5,
              feelslike_f: 61.7,
              windchill_c: 16.5,
              windchill_f: 61.7,
              heatindex_c: 16.5,
              heatindex_f: 61.7,
              dewpoint_c: 10.7,
              dewpoint_f: 51.3,
              will_it_rain: 1,
              chance_of_rain: 91,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 13.0,
              gust_kph: 20.9,
              uv: 1.0,
            },
            {
              time_epoch: 1639670400,
              time: "2021-12-16 18:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 237,
              wind_dir: "WSW",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 67,
              cloud: 74,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 10.6,
              dewpoint_f: 51.1,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9.0,
              vis_miles: 5.0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1.0,
            },
            {
              time_epoch: 1639674000,
              time: "2021-12-16 19:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 66,
              cloud: 61,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 10.4,
              dewpoint_f: 50.7,
              will_it_rain: 1,
              chance_of_rain: 90,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1.0,
            },
            {
              time_epoch: 1639677600,
              time: "2021-12-16 20:00",
              temp_c: 16.5,
              temp_f: 61.7,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 223,
              wind_dir: "SW",
              pressure_mb: 1019.0,
              pressure_in: 30.08,
              precip_mm: 1.9,
              precip_in: 0.07,
              humidity: 66,
              cloud: 65,
              feelslike_c: 16.5,
              feelslike_f: 61.7,
              windchill_c: 16.5,
              windchill_f: 61.7,
              heatindex_c: 16.5,
              heatindex_f: 61.7,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              will_it_rain: 1,
              chance_of_rain: 80,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 8.1,
              gust_kph: 13.0,
              uv: 1.0,
            },
            {
              time_epoch: 1639681200,
              time: "2021-12-16 21:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 212,
              wind_dir: "SSW",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 64,
              cloud: 59,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 9.9,
              dewpoint_f: 49.8,
              will_it_rain: 1,
              chance_of_rain: 89,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 1.0,
            },
            {
              time_epoch: 1639684800,
              time: "2021-12-16 22:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 200,
              wind_dir: "SSW",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.1,
              precip_in: 0.0,
              humidity: 62,
              cloud: 76,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 9.4,
              dewpoint_f: 48.9,
              will_it_rain: 1,
              chance_of_rain: 84,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1.0,
            },
            {
              time_epoch: 1639688400,
              time: "2021-12-16 23:00",
              temp_c: 16.4,
              temp_f: 61.5,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 197,
              wind_dir: "SSW",
              pressure_mb: 1018.0,
              pressure_in: 30.07,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 63,
              cloud: 64,
              feelslike_c: 16.4,
              feelslike_f: 61.5,
              windchill_c: 16.4,
              windchill_f: 61.5,
              heatindex_c: 16.4,
              heatindex_f: 61.5,
              dewpoint_c: 9.2,
              dewpoint_f: 48.6,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  }

  const budapest = {
    location: {
      name: "Budapest",
      region: "Budapest",
      country: "Hungary",
      lat: 47.5,
      lon: 19.08,
      tz_id: "Europe/Budapest",
      localtime_epoch: 1639417992,
      localtime: "2021-12-13 18:53",
    },
    current: {
      last_updated_epoch: 1639416600,
      last_updated: "2021-12-13 18:30",
      temp_c: 0.0,
      temp_f: 32.0,
      is_day: 0,
      condition: {
        text: "Clear",
        icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
        code: 1000,
      },
      wind_mph: 4.3,
      wind_kph: 6.8,
      wind_degree: 310,
      wind_dir: "NW",
      pressure_mb: 1024.0,
      pressure_in: 30.24,
      precip_mm: 0.0,
      precip_in: 0.0,
      humidity: 80,
      cloud: 0,
      feelslike_c: -2.1,
      feelslike_f: 28.3,
      vis_km: 10.0,
      vis_miles: 6.0,
      uv: 1.0,
      gust_mph: 5.6,
      gust_kph: 9.0,
    },
    forecast: {
      forecastday: [
        {
          date: "2021-12-13",
          date_epoch: 1639353600,
          day: {
            maxtemp_c: 4.2,
            maxtemp_f: 39.6,
            mintemp_c: -0.8,
            mintemp_f: 30.6,
            avgtemp_c: 1.2,
            avgtemp_f: 34.2,
            maxwind_mph: 4.7,
            maxwind_kph: 7.6,
            totalprecip_mm: 0.0,
            totalprecip_in: 0.0,
            avgvis_km: 10.0,
            avgvis_miles: 6.0,
            avghumidity: 73.0,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 1.0,
          },
          astro: {
            sunrise: "07:23 AM",
            sunset: "03:53 PM",
            moonrise: "01:14 PM",
            moonset: "01:20 AM",
            moon_phase: "First Quarter",
            moon_illumination: "61",
          },
          hour: [
            {
              time_epoch: 1639350000,
              time: "2021-12-13 00:00",
              temp_c: 0.0,
              temp_f: 32.0,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 335,
              wind_dir: "NNW",
              pressure_mb: 1023.0,
              pressure_in: 30.2,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 44,
              feelslike_c: -2.2,
              feelslike_f: 28.0,
              windchill_c: -2.2,
              windchill_f: 28.0,
              heatindex_c: 0.0,
              heatindex_f: 32.0,
              dewpoint_c: -3.7,
              dewpoint_f: 25.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 1.0,
            },
            {
              time_epoch: 1639353600,
              time: "2021-12-13 01:00",
              temp_c: 0.1,
              temp_f: 32.2,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1023.0,
              pressure_in: 30.22,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 74,
              cloud: 46,
              feelslike_c: -2.4,
              feelslike_f: 27.7,
              windchill_c: -2.4,
              windchill_f: 27.7,
              heatindex_c: 0.1,
              heatindex_f: 32.2,
              dewpoint_c: -3.9,
              dewpoint_f: 25.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 1.0,
            },
            {
              time_epoch: 1639357200,
              time: "2021-12-13 02:00",
              temp_c: 0.0,
              temp_f: 32.0,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 314,
              wind_dir: "NW",
              pressure_mb: 1023.0,
              pressure_in: 30.22,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 74,
              cloud: 44,
              feelslike_c: -2.6,
              feelslike_f: 27.3,
              windchill_c: -2.6,
              windchill_f: 27.3,
              heatindex_c: 0.0,
              heatindex_f: 32.0,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 1.0,
            },
            {
              time_epoch: 1639360800,
              time: "2021-12-13 03:00",
              temp_c: -0.2,
              temp_f: 31.6,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 316,
              wind_dir: "NW",
              pressure_mb: 1023.0,
              pressure_in: 30.22,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 74,
              cloud: 59,
              feelslike_c: -2.6,
              feelslike_f: 27.3,
              windchill_c: -2.6,
              windchill_f: 27.3,
              heatindex_c: -0.2,
              heatindex_f: 31.6,
              dewpoint_c: -4.2,
              dewpoint_f: 24.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 1.0,
            },
            {
              time_epoch: 1639364400,
              time: "2021-12-13 04:00",
              temp_c: -0.6,
              temp_f: 30.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 322,
              wind_dir: "NW",
              pressure_mb: 1023.0,
              pressure_in: 30.22,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 10,
              feelslike_c: -2.9,
              feelslike_f: 26.8,
              windchill_c: -2.9,
              windchill_f: 26.8,
              heatindex_c: -0.6,
              heatindex_f: 30.9,
              dewpoint_c: -4.3,
              dewpoint_f: 24.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1.0,
            },
            {
              time_epoch: 1639368000,
              time: "2021-12-13 05:00",
              temp_c: -0.7,
              temp_f: 30.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1024.0,
              pressure_in: 30.23,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 21,
              feelslike_c: -3.2,
              feelslike_f: 26.2,
              windchill_c: -3.2,
              windchill_f: 26.2,
              heatindex_c: -0.7,
              heatindex_f: 30.7,
              dewpoint_c: -4.4,
              dewpoint_f: 24.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1.0,
            },
            {
              time_epoch: 1639371600,
              time: "2021-12-13 06:00",
              temp_c: -0.8,
              temp_f: 30.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1024.0,
              pressure_in: 30.24,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 10,
              feelslike_c: -3.1,
              feelslike_f: 26.4,
              windchill_c: -3.1,
              windchill_f: 26.4,
              heatindex_c: -0.8,
              heatindex_f: 30.6,
              dewpoint_c: -4.4,
              dewpoint_f: 24.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1.0,
            },
            {
              time_epoch: 1639375200,
              time: "2021-12-13 07:00",
              temp_c: -0.8,
              temp_f: 30.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 317,
              wind_dir: "NW",
              pressure_mb: 1024.0,
              pressure_in: 30.25,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 3,
              feelslike_c: -2.8,
              feelslike_f: 27.0,
              windchill_c: -2.8,
              windchill_f: 27.0,
              heatindex_c: -0.8,
              heatindex_f: 30.6,
              dewpoint_c: -4.5,
              dewpoint_f: 23.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1.0,
            },
            {
              time_epoch: 1639378800,
              time: "2021-12-13 08:00",
              temp_c: -0.6,
              temp_f: 30.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 75,
              cloud: 2,
              feelslike_c: -2.6,
              feelslike_f: 27.3,
              windchill_c: -2.6,
              windchill_f: 27.3,
              heatindex_c: -0.6,
              heatindex_f: 30.9,
              dewpoint_c: -4.4,
              dewpoint_f: 24.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 2.0,
            },
            {
              time_epoch: 1639382400,
              time: "2021-12-13 09:00",
              temp_c: 0.3,
              temp_f: 32.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 71,
              cloud: 1,
              feelslike_c: -1.7,
              feelslike_f: 28.9,
              windchill_c: -1.7,
              windchill_f: 28.9,
              heatindex_c: 0.3,
              heatindex_f: 32.5,
              dewpoint_c: -4.2,
              dewpoint_f: 24.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.0,
              gust_kph: 9.7,
              uv: 2.0,
            },
            {
              time_epoch: 1639386000,
              time: "2021-12-13 10:00",
              temp_c: 1.3,
              temp_f: 34.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 67,
              cloud: 0,
              feelslike_c: -0.8,
              feelslike_f: 30.6,
              windchill_c: -0.8,
              windchill_f: 30.6,
              heatindex_c: 1.3,
              heatindex_f: 34.3,
              dewpoint_c: -4.1,
              dewpoint_f: 24.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 6.0,
              gust_kph: 9.7,
              uv: 2.0,
            },
            {
              time_epoch: 1639389600,
              time: "2021-12-13 11:00",
              temp_c: 3.4,
              temp_f: 38.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 65,
              cloud: 2,
              feelslike_c: 1.7,
              feelslike_f: 35.1,
              windchill_c: 1.7,
              windchill_f: 35.1,
              heatindex_c: 3.4,
              heatindex_f: 38.1,
              dewpoint_c: -2.5,
              dewpoint_f: 27.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.7,
              gust_kph: 7.6,
              uv: 2.0,
            },
            {
              time_epoch: 1639393200,
              time: "2021-12-13 12:00",
              temp_c: 3.9,
              temp_f: 39.0,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 316,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 64,
              cloud: 4,
              feelslike_c: 2.5,
              feelslike_f: 36.5,
              windchill_c: 2.5,
              windchill_f: 36.5,
              heatindex_c: 3.9,
              heatindex_f: 39.0,
              dewpoint_c: -2.3,
              dewpoint_f: 27.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.0,
              gust_kph: 6.5,
              uv: 2.0,
            },
            {
              time_epoch: 1639396800,
              time: "2021-12-13 13:00",
              temp_c: 4.1,
              temp_f: 39.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 315,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.26,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 64,
              cloud: 6,
              feelslike_c: 2.9,
              feelslike_f: 37.2,
              windchill_c: 2.9,
              windchill_f: 37.2,
              heatindex_c: 4.1,
              heatindex_f: 39.4,
              dewpoint_c: -2.1,
              dewpoint_f: 28.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 3.8,
              gust_kph: 6.1,
              uv: 2.0,
            },
            {
              time_epoch: 1639400400,
              time: "2021-12-13 14:00",
              temp_c: 4.2,
              temp_f: 39.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 318,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 65,
              cloud: 7,
              feelslike_c: 2.8,
              feelslike_f: 37.0,
              windchill_c: 2.8,
              windchill_f: 37.0,
              heatindex_c: 4.2,
              heatindex_f: 39.6,
              dewpoint_c: -1.7,
              dewpoint_f: 28.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.5,
              gust_kph: 7.2,
              uv: 2.0,
            },
            {
              time_epoch: 1639404000,
              time: "2021-12-13 15:00",
              temp_c: 3.6,
              temp_f: 38.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 320,
              wind_dir: "NW",
              pressure_mb: 1025.0,
              pressure_in: 30.27,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 70,
              cloud: 7,
              feelslike_c: 2.1,
              feelslike_f: 35.8,
              windchill_c: 2.1,
              windchill_f: 35.8,
              heatindex_c: 3.6,
              heatindex_f: 38.5,
              dewpoint_c: -1.3,
              dewpoint_f: 29.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.7,
              gust_kph: 7.6,
              uv: 2.0,
            },
            {
              time_epoch: 1639407600,
              time: "2021-12-13 16:00",
              temp_c: 2.7,
              temp_f: 36.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.0,
              wind_kph: 6.5,
              wind_degree: 324,
              wind_dir: "NW",
              pressure_mb: 1026.0,
              pressure_in: 30.28,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 6,
              feelslike_c: 0.9,
              feelslike_f: 33.6,
              windchill_c: 0.9,
              windchill_f: 33.6,
              heatindex_c: 2.7,
              heatindex_f: 36.9,
              dewpoint_c: -1.1,
              dewpoint_f: 30.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.0,
              uv: 1.0,
            },
            {
              time_epoch: 1639411200,
              time: "2021-12-13 17:00",
              temp_c: 2.4,
              temp_f: 36.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 338,
              wind_dir: "NNW",
              pressure_mb: 1026.0,
              pressure_in: 30.3,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 7,
              feelslike_c: 0.7,
              feelslike_f: 33.3,
              windchill_c: 0.7,
              windchill_f: 33.3,
              heatindex_c: 2.4,
              heatindex_f: 36.3,
              dewpoint_c: -1.0,
              dewpoint_f: 30.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.6,
              gust_kph: 9.0,
              uv: 1.0,
            },
            {
              time_epoch: 1639414800,
              time: "2021-12-13 18:00",
              temp_c: 2.3,
              temp_f: 36.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 340,
              wind_dir: "NNW",
              pressure_mb: 1026.0,
              pressure_in: 30.31,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 8,
              feelslike_c: 0.8,
              feelslike_f: 33.4,
              windchill_c: 0.8,
              windchill_f: 33.4,
              heatindex_c: 2.3,
              heatindex_f: 36.1,
              dewpoint_c: -1.1,
              dewpoint_f: 30.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 1.0,
            },
            {
              time_epoch: 1639418400,
              time: "2021-12-13 19:00",
              temp_c: 2.0,
              temp_f: 35.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 340,
              wind_dir: "NNW",
              pressure_mb: 1027.0,
              pressure_in: 30.32,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 78,
              cloud: 11,
              feelslike_c: 0.7,
              feelslike_f: 33.3,
              windchill_c: 0.7,
              windchill_f: 33.3,
              heatindex_c: 2.0,
              heatindex_f: 35.6,
              dewpoint_c: -1.4,
              dewpoint_f: 29.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.7,
              gust_kph: 7.6,
              uv: 1.0,
            },
            {
              time_epoch: 1639422000,
              time: "2021-12-13 20:00",
              temp_c: 0.7,
              temp_f: 33.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 353,
              wind_dir: "N",
              pressure_mb: 1027.0,
              pressure_in: 30.33,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 77,
              cloud: 14,
              feelslike_c: -0.6,
              feelslike_f: 30.9,
              windchill_c: -0.6,
              windchill_f: 30.9,
              heatindex_c: 0.7,
              heatindex_f: 33.3,
              dewpoint_c: -2.8,
              dewpoint_f: 27.0,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 1.0,
            },
            {
              time_epoch: 1639425600,
              time: "2021-12-13 21:00",
              temp_c: 0.6,
              temp_f: 33.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 346,
              wind_dir: "NNW",
              pressure_mb: 1027.0,
              pressure_in: 30.34,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 9,
              feelslike_c: -0.8,
              feelslike_f: 30.6,
              windchill_c: -0.8,
              windchill_f: 30.6,
              heatindex_c: 0.6,
              heatindex_f: 33.1,
              dewpoint_c: -3.1,
              dewpoint_f: 26.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 1.0,
            },
            {
              time_epoch: 1639429200,
              time: "2021-12-13 22:00",
              temp_c: 0.6,
              temp_f: 33.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5.0,
              wind_degree: 343,
              wind_dir: "NNW",
              pressure_mb: 1028.0,
              pressure_in: 30.35,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 6,
              feelslike_c: -0.9,
              feelslike_f: 30.4,
              windchill_c: -0.9,
              windchill_f: 30.4,
              heatindex_c: 0.6,
              heatindex_f: 33.1,
              dewpoint_c: -3.1,
              dewpoint_f: 26.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 1.0,
            },
            {
              time_epoch: 1639432800,
              time: "2021-12-13 23:00",
              temp_c: 0.6,
              temp_f: 33.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 346,
              wind_dir: "NNW",
              pressure_mb: 1028.0,
              pressure_in: 30.35,
              precip_mm: 0.0,
              precip_in: 0.0,
              humidity: 76,
              cloud: 7,
              feelslike_c: -0.6,
              feelslike_f: 30.9,
              windchill_c: -0.6,
              windchill_f: 30.9,
              heatindex_c: 0.6,
              heatindex_f: 33.1,
              dewpoint_c: -3.2,
              dewpoint_f: 26.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10.0,
              vis_miles: 6.0,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 1.0,
            },
          ],
        },
      ],
    },
  }

  const rome = {
    "location": {
      "name": "Rome",
      "region": "Lazio",
      "country": "Italy",
      "lat": 41.9,
      "lon": 12.48,
      "tz_id": "Europe/Rome",
      "localtime_epoch": 1644790223,
      "localtime": "2022-02-13 23:10"
    },
    "current": {
      "last_updated_epoch": 1644786000,
      "last_updated": "2022-02-13 22:00",
      "temp_c": 10.0,
      "temp_f": 50.0,
      "is_day": 0,
      "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        "code": 1003
      },
      "wind_mph": 8.1,
      "wind_kph": 13.0,
      "wind_degree": 100,
      "wind_dir": "E",
      "pressure_mb": 1023.0,
      "pressure_in": 30.21,
      "precip_mm": 0.2,
      "precip_in": 0.01,
      "humidity": 82,
      "cloud": 50,
      "feelslike_c": 9.4,
      "feelslike_f": 49.0,
      "vis_km": 10.0,
      "vis_miles": 6.0,
      "uv": 1.0,
      "gust_mph": 6.9,
      "gust_kph": 11.2
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2022-02-13",
          "date_epoch": 1644710400,
          "day": {
            "maxtemp_c": 14.6,
            "maxtemp_f": 58.3,
            "mintemp_c": 8.4,
            "mintemp_f": 47.1,
            "avgtemp_c": 10.6,
            "avgtemp_f": 51.1,
            "maxwind_mph": 7.6,
            "maxwind_kph": 12.2,
            "totalprecip_mm": 0.3,
            "totalprecip_in": 0.01,
            "avgvis_km": 10.0,
            "avgvis_miles": 6.0,
            "avghumidity": 65.0,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 69,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "uv": 1.0
          },
          "astro": {
            "sunrise": "07:09 AM",
            "sunset": "05:41 PM",
            "moonrise": "02:17 PM",
            "moonset": "05:26 AM",
            "moon_phase": "Waxing Gibbous",
            "moon_illumination": "85"
          },
          "hour": [
            {
              "time_epoch": 1644706800,
              "time": "2022-02-13 00:00",
              "temp_c": 9.3,
              "temp_f": 48.7,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 6,
              "wind_dir": "N",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 64,
              "cloud": 63,
              "feelslike_c": 8.2,
              "feelslike_f": 46.8,
              "windchill_c": 8.2,
              "windchill_f": 46.8,
              "heatindex_c": 9.3,
              "heatindex_f": 48.7,
              "dewpoint_c": 3.0,
              "dewpoint_f": 37.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.3,
              "gust_kph": 13.3,
              "uv": 1.0
            },
            {
              "time_epoch": 1644710400,
              "time": "2022-02-13 01:00",
              "temp_c": 9.0,
              "temp_f": 48.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 7,
              "wind_dir": "N",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 65,
              "cloud": 57,
              "feelslike_c": 7.8,
              "feelslike_f": 46.0,
              "windchill_c": 7.8,
              "windchill_f": 46.0,
              "heatindex_c": 9.0,
              "heatindex_f": 48.2,
              "dewpoint_c": 2.8,
              "dewpoint_f": 37.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.5,
              "gust_kph": 13.7,
              "uv": 1.0
            },
            {
              "time_epoch": 1644714000,
              "time": "2022-02-13 02:00",
              "temp_c": 8.6,
              "temp_f": 47.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 9,
              "wind_dir": "N",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 51,
              "feelslike_c": 7.4,
              "feelslike_f": 45.3,
              "windchill_c": 7.4,
              "windchill_f": 45.3,
              "heatindex_c": 8.6,
              "heatindex_f": 47.5,
              "dewpoint_c": 2.6,
              "dewpoint_f": 36.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.7,
              "gust_kph": 14.0,
              "uv": 1.0
            },
            {
              "time_epoch": 1644717600,
              "time": "2022-02-13 03:00",
              "temp_c": 8.5,
              "temp_f": 47.3,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 13,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.28,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 51,
              "feelslike_c": 7.3,
              "feelslike_f": 45.1,
              "windchill_c": 7.3,
              "windchill_f": 45.1,
              "heatindex_c": 8.5,
              "heatindex_f": 47.3,
              "dewpoint_c": 2.5,
              "dewpoint_f": 36.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.3,
              "gust_kph": 13.3,
              "uv": 1.0
            },
            {
              "time_epoch": 1644721200,
              "time": "2022-02-13 04:00",
              "temp_c": 8.8,
              "temp_f": 47.8,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 19,
              "wind_dir": "NNE",
              "pressure_mb": 1025.0,
              "pressure_in": 30.28,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 62,
              "feelslike_c": 8.2,
              "feelslike_f": 46.8,
              "windchill_c": 8.2,
              "windchill_f": 46.8,
              "heatindex_c": 8.8,
              "heatindex_f": 47.8,
              "dewpoint_c": 2.8,
              "dewpoint_f": 37.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.0,
              "gust_kph": 9.7,
              "uv": 1.0
            },
            {
              "time_epoch": 1644724800,
              "time": "2022-02-13 05:00",
              "temp_c": 8.7,
              "temp_f": 47.7,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 20,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.28,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 65,
              "feelslike_c": 7.9,
              "feelslike_f": 46.2,
              "windchill_c": 7.9,
              "windchill_f": 46.2,
              "heatindex_c": 8.7,
              "heatindex_f": 47.7,
              "dewpoint_c": 2.7,
              "dewpoint_f": 36.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.5,
              "gust_kph": 10.4,
              "uv": 1.0
            },
            {
              "time_epoch": 1644728400,
              "time": "2022-02-13 06:00",
              "temp_c": 8.5,
              "temp_f": 47.3,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 25,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.28,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 44,
              "feelslike_c": 7.7,
              "feelslike_f": 45.9,
              "windchill_c": 7.7,
              "windchill_f": 45.9,
              "heatindex_c": 8.5,
              "heatindex_f": 47.3,
              "dewpoint_c": 2.5,
              "dewpoint_f": 36.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1644732000,
              "time": "2022-02-13 07:00",
              "temp_c": 8.4,
              "temp_f": 47.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 19,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 45,
              "feelslike_c": 7.7,
              "feelslike_f": 45.9,
              "windchill_c": 7.7,
              "windchill_f": 45.9,
              "heatindex_c": 8.4,
              "heatindex_f": 47.1,
              "dewpoint_c": 2.4,
              "dewpoint_f": 36.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1644735600,
              "time": "2022-02-13 08:00",
              "temp_c": 8.6,
              "temp_f": 47.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 13,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 67,
              "cloud": 47,
              "feelslike_c": 8.0,
              "feelslike_f": 46.4,
              "windchill_c": 8.0,
              "windchill_f": 46.4,
              "heatindex_c": 8.6,
              "heatindex_f": 47.5,
              "dewpoint_c": 2.8,
              "dewpoint_f": 37.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 5.6,
              "gust_kph": 9.0,
              "uv": 3.0
            },
            {
              "time_epoch": 1644739200,
              "time": "2022-02-13 09:00",
              "temp_c": 10.1,
              "temp_f": 50.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.1,
              "wind_kph": 5.0,
              "wind_degree": 27,
              "wind_dir": "NNE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 64,
              "cloud": 46,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 10.1,
              "heatindex_f": 50.2,
              "dewpoint_c": 3.5,
              "dewpoint_f": 38.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 4.0,
              "gust_kph": 6.5,
              "uv": 4.0
            },
            {
              "time_epoch": 1644742800,
              "time": "2022-02-13 10:00",
              "temp_c": 11.7,
              "temp_f": 53.1,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 59,
              "wind_dir": "ENE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 61,
              "cloud": 45,
              "feelslike_c": 12.1,
              "feelslike_f": 53.8,
              "windchill_c": 12.1,
              "windchill_f": 53.8,
              "heatindex_c": 11.7,
              "heatindex_f": 53.1,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 2.7,
              "gust_kph": 4.3,
              "uv": 4.0
            },
            {
              "time_epoch": 1644746400,
              "time": "2022-02-13 11:00",
              "temp_c": 13.0,
              "temp_f": 55.4,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 1.6,
              "wind_kph": 2.5,
              "wind_degree": 116,
              "wind_dir": "ESE",
              "pressure_mb": 1026.0,
              "pressure_in": 30.29,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 57,
              "cloud": 48,
              "feelslike_c": 13.0,
              "feelslike_f": 55.4,
              "windchill_c": 13.0,
              "windchill_f": 55.4,
              "heatindex_c": 13.0,
              "heatindex_f": 55.4,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 1.8,
              "gust_kph": 2.9,
              "uv": 4.0
            },
            {
              "time_epoch": 1644750000,
              "time": "2022-02-13 12:00",
              "temp_c": 13.8,
              "temp_f": 56.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 179,
              "wind_dir": "S",
              "pressure_mb": 1025.0,
              "pressure_in": 30.28,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 55,
              "cloud": 50,
              "feelslike_c": 14.2,
              "feelslike_f": 57.6,
              "windchill_c": 14.2,
              "windchill_f": 57.6,
              "heatindex_c": 13.8,
              "heatindex_f": 56.8,
              "dewpoint_c": 4.9,
              "dewpoint_f": 40.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 3.1,
              "gust_kph": 5.0,
              "uv": 4.0
            },
            {
              "time_epoch": 1644753600,
              "time": "2022-02-13 13:00",
              "temp_c": 14.3,
              "temp_f": 57.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 193,
              "wind_dir": "SSW",
              "pressure_mb": 1025.0,
              "pressure_in": 30.25,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 53,
              "cloud": 51,
              "feelslike_c": 14.1,
              "feelslike_f": 57.4,
              "windchill_c": 14.1,
              "windchill_f": 57.4,
              "heatindex_c": 14.3,
              "heatindex_f": 57.7,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 5.4,
              "gust_kph": 8.6,
              "uv": 4.0
            },
            {
              "time_epoch": 1644757200,
              "time": "2022-02-13 14:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 6.0,
              "wind_kph": 9.7,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 1024.0,
              "pressure_in": 30.23,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 52,
              "cloud": 84,
              "feelslike_c": 14.2,
              "feelslike_f": 57.6,
              "windchill_c": 14.2,
              "windchill_f": 57.6,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 3.0
            },
            {
              "time_epoch": 1644760800,
              "time": "2022-02-13 15:00",
              "temp_c": 14.5,
              "temp_f": 58.1,
              "is_day": 1,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
              },
              "wind_mph": 7.4,
              "wind_kph": 11.9,
              "wind_degree": 204,
              "wind_dir": "SSW",
              "pressure_mb": 1023.0,
              "pressure_in": 30.22,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 52,
              "cloud": 98,
              "feelslike_c": 13.8,
              "feelslike_f": 56.8,
              "windchill_c": 13.8,
              "windchill_f": 56.8,
              "heatindex_c": 14.5,
              "heatindex_f": 58.1,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.5,
              "gust_kph": 13.7,
              "uv": 3.0
            },
            {
              "time_epoch": 1644764400,
              "time": "2022-02-13 16:00",
              "temp_c": 13.5,
              "temp_f": 56.3,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 195,
              "wind_dir": "SSW",
              "pressure_mb": 1023.0,
              "pressure_in": 30.22,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 57,
              "cloud": 67,
              "feelslike_c": 12.5,
              "feelslike_f": 54.5,
              "windchill_c": 12.5,
              "windchill_f": 54.5,
              "heatindex_c": 13.5,
              "heatindex_f": 56.3,
              "dewpoint_c": 5.2,
              "dewpoint_f": 41.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 3.0
            },
            {
              "time_epoch": 1644768000,
              "time": "2022-02-13 17:00",
              "temp_c": 12.4,
              "temp_f": 54.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 188,
              "wind_dir": "S",
              "pressure_mb": 1023.0,
              "pressure_in": 30.21,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 63,
              "cloud": 53,
              "feelslike_c": 11.3,
              "feelslike_f": 52.3,
              "windchill_c": 11.3,
              "windchill_f": 52.3,
              "heatindex_c": 12.4,
              "heatindex_f": 54.3,
              "dewpoint_c": 5.7,
              "dewpoint_f": 42.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 4.0
            },
            {
              "time_epoch": 1644771600,
              "time": "2022-02-13 18:00",
              "temp_c": 10.8,
              "temp_f": 51.4,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 5.6,
              "wind_kph": 9.0,
              "wind_degree": 183,
              "wind_dir": "S",
              "pressure_mb": 1023.0,
              "pressure_in": 30.22,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 71,
              "cloud": 61,
              "feelslike_c": 9.8,
              "feelslike_f": 49.6,
              "windchill_c": 9.8,
              "windchill_f": 49.6,
              "heatindex_c": 10.8,
              "heatindex_f": 51.4,
              "dewpoint_c": 5.7,
              "dewpoint_f": 42.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1644775200,
              "time": "2022-02-13 19:00",
              "temp_c": 10.4,
              "temp_f": 50.7,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 175,
              "wind_dir": "S",
              "pressure_mb": 1024.0,
              "pressure_in": 30.22,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 74,
              "cloud": 67,
              "feelslike_c": 9.6,
              "feelslike_f": 49.3,
              "windchill_c": 9.6,
              "windchill_f": 49.3,
              "heatindex_c": 10.4,
              "heatindex_f": 50.7,
              "dewpoint_c": 6.0,
              "dewpoint_f": 42.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.1,
              "gust_kph": 13.0,
              "uv": 1.0
            },
            {
              "time_epoch": 1644778800,
              "time": "2022-02-13 20:00",
              "temp_c": 10.3,
              "temp_f": 50.5,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 4.0,
              "wind_kph": 6.5,
              "wind_degree": 169,
              "wind_dir": "S",
              "pressure_mb": 1024.0,
              "pressure_in": 30.23,
              "precip_mm": 0.1,
              "precip_in": 0.0,
              "humidity": 76,
              "cloud": 66,
              "feelslike_c": 9.7,
              "feelslike_f": 49.5,
              "windchill_c": 9.7,
              "windchill_f": 49.5,
              "heatindex_c": 10.3,
              "heatindex_f": 50.5,
              "dewpoint_c": 6.3,
              "dewpoint_f": 43.3,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1644782400,
              "time": "2022-02-13 21:00",
              "temp_c": 9.7,
              "temp_f": 49.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.0,
              "wind_kph": 6.5,
              "wind_degree": 159,
              "wind_dir": "SSE",
              "pressure_mb": 1024.0,
              "pressure_in": 30.23,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 79,
              "cloud": 62,
              "feelslike_c": 9.0,
              "feelslike_f": 48.2,
              "windchill_c": 9.0,
              "windchill_f": 48.2,
              "heatindex_c": 9.7,
              "heatindex_f": 49.5,
              "dewpoint_c": 6.2,
              "dewpoint_f": 43.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1644786000,
              "time": "2022-02-13 22:00",
              "temp_c": 9.2,
              "temp_f": 48.6,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 161,
              "wind_dir": "SSE",
              "pressure_mb": 1024.0,
              "pressure_in": 30.23,
              "precip_mm": 0.2,
              "precip_in": 0.01,
              "humidity": 82,
              "cloud": 70,
              "feelslike_c": 8.5,
              "feelslike_f": 47.3,
              "windchill_c": 8.5,
              "windchill_f": 47.3,
              "heatindex_c": 9.2,
              "heatindex_f": 48.6,
              "dewpoint_c": 6.2,
              "dewpoint_f": 43.2,
              "will_it_rain": 0,
              "chance_of_rain": 69,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1644789600,
              "time": "2022-02-13 23:00",
              "temp_c": 8.6,
              "temp_f": 47.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.1,
              "wind_kph": 5.0,
              "wind_degree": 166,
              "wind_dir": "SSE",
              "pressure_mb": 1023.0,
              "pressure_in": 30.22,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 84,
              "cloud": 36,
              "feelslike_c": 8.2,
              "feelslike_f": 46.8,
              "windchill_c": 8.2,
              "windchill_f": 46.8,
              "heatindex_c": 8.6,
              "heatindex_f": 47.5,
              "dewpoint_c": 6.1,
              "dewpoint_f": 43.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 5.8,
              "gust_kph": 9.4,
              "uv": 1.0
            }
          ]
        }
      ]
    }
  }

  return { telAviv, budapest, rome }
}

